### ISSUE TITLE
Crash when instance-group restarts scheduler

### ISSUE THREAD

**Issue by future-mano** [future-architect/gcp-instance-scheduler#36]
## Describe the bug
Crash when instance-group restart.

## Stacktrace Copy

```
2019-08-28 08:30:05.054 JST
ReceiveEvent
711200138983436
2019/08/27 23:30:05 Some error occurred in starting instances group: label: restore-size-app-pool value is not number format?
2019-08-28 08:30:05.055 JST
ReceiveEvent
711200138983436
Function execution took 1369 ms, finished with status: 'crash'
2019-08-28 08:30:06.062 JST
ReceiveEvent
711200138983436
Function panic: runtime error: invalid memory address or nil pointer dereference goroutine 11 [running]: runtime/debug.Stack(0xc000138ee8, 0xc23200, 0x13c2db0) /go/src/runtime/debug/stack.go:24 +0xa7 main.executeFunction.func1(0xe314a0, 0xc000292000) /tmp/sgb/staging/srv/worker.go:116 +0x6e panic(0xc23200, 0x13c2db0) /go/src/runtime/panic.go:513 +0x1b9 github.com/future-architect/gcp-instance-scheduler/model.(*Report).Show(0x0, 0x0, 0x0, 0x0) /tmp/sgb/staging/srv/files/model/model.go:41 +0x3a github.com/future-architect/gcp-instance-scheduler/scheduler.Restart(0x2b28e9b3a0d0, 0xc00006e720, 0xc000139498, 0x1, 0x1) /tmp/sgb/staging/srv/files/scheduler/scheduler.go:120 +0x138 github.com/future-architect/gcp-instance-scheduler.ReceiveEvent(0x2b28e9b3a0d0, 0xc00006e720, 0xc00025c120, 0x0, 0x0) /tmp/sgb/staging/srv/files/scheduler.go:60 +0x49a reflect.Value.call(0xbe63c0, 0xdabed8, 0x13, 0xd7e66d, 0x4, 0xc000139b68, 0x2, 0x2, 0xc000139b40, 0xc00006e720, ...) /go/src/reflect/value.go:447 +0x454 reflect.Value.Call(0xbe63c0, 0xdabed8, 0x13, 0xc000139b68, 0x2, 0x2, 0x0, 0x0, 0xc0000721e0) /go/src/reflect/value.go:308 +0xa4 main.executeFunction(0xe314a0, 0xc000292000, 0xc0000f4900) /tmp/sgb/staging/srv/worker.go:187 +0x7a1 net/http.HandlerFunc.ServeHTTP(0xdaced0, 0xe314a0, 0xc000292000, 0xc0000f4900) /go/src/net/http/server.go:1964 +0x44 net/http.(*ServeMux).ServeHTTP(0x13d6860, 0xe314a0, 0xc000292000, 0xc0000f4900) /go/src/net/http/server.go:2361 +0x127 net/http.serverHandler.ServeHTTP(0xc000089a00, 0xe314a0, 0xc000292000, 0xc0000f4900) /go/src/net/http/server.go:2741 +0xab net/http.(*conn).serve(0xc000266460, 0xe31a60, 0xc00005b740) /go/src/net/http/server.go:1847 +0x646 created by net/http.(*Server).Serve /go/src/net/http/server.go:2851 +0x2f5
```

## To Reproduce

There are instance group that not have state-scheduler label

## Expected behavior
not crash

## Additional context

This line.
https://github.com/future-architect/gcp-instance-scheduler/blob/master/operator/gke.go#L103

**Comment by laqiiz** [comment]
done in #39
